/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module muldiv_12 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] o,
    output reg [2:0] error,
    output reg overflow
  );
  
  
  
  always @* begin
    o = 1'h0;
    error = 1'h0;
    overflow = 1'h0;
    
    case (alufn[0+0-:1])
      1'h0: begin
        o = a * b;
      end
      1'h1: begin
        if (b == 1'h0) begin
          error = 3'h3;
        end else begin
          o = $signed(a) / $signed(b);
        end
      end
    endcase
    if (a * b < $signed(17'h18000) | a * b > 15'h7fff) begin
      overflow = 1'h1;
    end
  end
endmodule
